# Generated by Django 2.1.1 on 2018-10-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myins', '0002_inspiration_reference_trophy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='trophy',
            name='Product',
        ),
        migrations.AddField(
            model_name='reference',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trophy',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
